export const defaultTheme = {
  colorBlackForText: "#333333",
  colorWhite: "#ffffff",
  colorGray: "#f6f6f6",
  colorForBackground: "#d8ecfe",
  colorForFarmLight: "#e1edce",
  colorForFarmDark: "#88aa4d",
  colorForShopLight: "#f8ddd7",
  colorForShopDark: "#f75531",
  colorForButton: "#fc9b27",
  colorForButtonHover: "#fc7427",
  pagePadding: "90px",
  indent: "20px",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: "18px",
  fontSizeDefaultSmall: "14px; line-height: 150%",
  footerHeight: "80px",
  pageWidth: "1280px",
};
